/*
3474. Lexicographically Smallest Generated String
Solved
Hard
Topics
premium lock icon
Companies
Hint
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
*/
/**
 * @param {string} str1
 * @param {string} str2
 * @return {string}
 */
var generateString = function (str1, str2) {
  const n = str1.length;
  const m = str2.length;

  const N = n + m - 1;
  const word = new Array(N).fill("$");
  const canChange = new Array(N).fill(false);

  function isSame(word, str, i, m) {
    for (let j = 0; j < m; j++) {
      if (word[i] !== str[j]) return false;
      i++;
    }

    return true;
  }

  // Step 1. Process the 'T' in str1
  for (let i = 0; i < n; i++) {
    if (str1[i] === "T") {
      let k = i;
      for (let j = 0; j < m; j++) {
        if (word[k] !== "$" && word[k] !== str2[j]) return "";
        word[k] = str2[j];
        k++;
      }
    }
  }

  // Step 2. Fill the remaining spaces with 'a' (possibly lexicographically smallest alphabet)
  for (let i = 0; i < N; i++) {
    if (word[i] === "$") {
      word[i] = "a";
      canChange[i] = true;
    }
  }

  // Step 3. Process the 'F' in str1
  for (let i = 0; i < n; i++) {
    if (str1[i] === "F") {
      if (isSame(word, str2, i, m)) {
        // If same, then we need to change word[i] to make it unequal

        let changed = false;
        for (let k = i + m - 1; k >= i; k--) {
          if (canChange[k] === true) {
            word[k] = "b";
            changed = true;
            break;
          }
        }

        if (changed === false) {
          // making unequal is not possible
          return "";
        }
      }
    }
  }
  return word.join("");
};

/**
 * @param {string} str1
 * @param {string} str2
 * @return {string}
 */
var lexicographicallySmallestString = function (str1, str2) {
  const n = str1.length;
  const m = str2.length;
  const len = n + m - 1;

  const word = new Uint8Array(len);
  const isFixed = new Uint8Array(len);

  const str2Codes = new Uint8Array(m);
  for (let i = 0; i < m; i++) str2Codes[i] = str2.charCodeAt(i);

  // Step 1: Satisfy all 'T' constraints (Mandatory matches)
  for (let i = 0; i < n; i++) {
    if (str1[i] === "T") {
      for (let j = 0; j < m; j++) {
        const targetChar = str2Codes[j];
        const pos = i + j;
        // If this position is already fixed to a different character, it's impossible
        if (isFixed[pos] && word[pos] !== targetChar) return "";
        word[pos] = targetChar;
        isFixed[pos] = 1;
      }
    }
  }

  // Step 2: Fill non-fixed positions with 'a' for lexicographical smallest start
  for (let i = 0; i < len; i++) {
    if (!isFixed[i]) word[i] = 97; // ASCII for 'a'
  }

  // Step 3: Satisfy 'F' constraints (Mandatory non-matches)
  let i = 0;
  while (i < n) {
    if (str1[i] === "F") {
      let match = true;
      for (let k = 0; k < m; k++) {
        if (word[i + k] !== str2Codes[k]) {
          match = false;
          break;
        }
      }

      // If the current substring matches str2 but it should not
      if (match) {
        let j = -1;
        // Find the rightmost character in the window that isn't fixed by a 'T'
        for (let k = i + m - 1; k >= i; k--) {
          if (!isFixed[k]) {
            j = k;
            break;
          }
        }

        // If all characters are fixed and they form a match, constraint is impossible
        if (j === -1) return "";

        // Increment the character to break the match (e.g., 'a' to 'b')
        word[j]++;
        if (word[j] > 122) return ""; // Exceeded 'z'

        // Re-verify from the earliest window affected by the change at index j
        i = Math.max(0, j - m + 1);
      } else {
        i++;
      }
    } else {
      i++;
    }
  }

  // Convert character codes back to a string safely
  let result = "";
  const CHUNK_SIZE = 16384;
  for (let i = 0; i < word.length; i += CHUNK_SIZE) {
    result += String.fromCharCode(...word.subarray(i, i + CHUNK_SIZE));
  }
  return result;
};
